service: craft-circle-be
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: dev

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        AttributeDefinitions: 
          - AttributeName: itemId 
            AttributeType: S